version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pmt
      POSTGRES_USER: pmt
      POSTGRES_PASSWORD: pmt
    ports:
      - "5432:5432"
    volumes:
      - pmt_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmt -d pmt"]
      interval: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:postgresql://db:5432/pmt}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-pmt}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-pmt}

      APP_MAIL_FROM: ${APP_MAIL_FROM:-no-reply@pmt.local}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-}
      SPRING_MAIL_SMTP_AUTH: ${SPRING_MAIL_SMTP_AUTH:-true}
      SPRING_MAIL_STARTTLS: ${SPRING_MAIL_STARTTLS:-true}

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  pmt_pgdata:
