version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pmt
      POSTGRES_USER: pmt
      POSTGRES_PASSWORD: pmt
    ports:
      - "5432:5432"
    volumes:
      - pmt_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmt -d pmt"]
      interval: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pmt
      SPRING_DATASOURCE_USERNAME: pmt
      SPRING_DATASOURCE_PASSWORD: pmt

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  pmt_pgdata:
